### ISSUE TITLE
Allow inverted order of language and keywords.

### ISSUE THREAD

**Issue by SiggiGue** [SiggiGue/i18nkiss#1]
```yaml
hi:
    de: Hey
    en: Hi
```
instead of:
```yaml

en: 
    hi: Hi
de: 
    hi: Hey
```
